### ISSUE TITLE
cannot compile multi_threaded_copy{,_overlap} because of argument mismatch to `std::swap`

### ISSUE THREAD

**Issue by bertwesarg** [NVIDIA/multi-gpu-programming-models#10]
I get the following compile error with GCC 10 and CUDA 11.4:

```console
jacobi.cu(280): error: no instance of overloaded function "std::swap" matches the argument list
            argument types are: (real *[32], real *)

1 error detected in the compilation of "jacobi.cu".
```

I assume it must be:

```diff
-            std::swap(a_new, a);
+            std::swap(a_new[dev_id], a);
```

but would like to have confirmation first.

Thanks.

**Comment by jirikraus** [comment]
Thanks for the report. Yes that is right it should be `std::swap(a_new[dev_id], a);`. I will push a fix soon.

**Comment by jirikraus** [comment]
Fixed with https://github.com/NVIDIA/multi-gpu-programming-models/commit/79a36145dd4f137b55371d72f4a566aef4e262eb. Closing this.
