### ISSUE TITLE
mpi executable crashes with segmentation fault

### ISSUE THREAD

**Issue by eyalroz** [NVIDIA/multi-gpu-programming-models#15]
I'm using the following commands to build the `mpi` executable:
```
nvcc -forward-unknown-to-host-compiler -DUSE_NVTX -isystem=/usr/local/cuda/include --generate-code=arch=compute_61,code=[compute_61,sm_61] -Xptxas --optimize-float-atomics --std=c++14 -c jacobi_kernels.cu -o jacobi_kernels.cu.o
c++ -DSKIP_CUDA_AWARENESS_CHECK -DUSE_NVTX -isystem /usr/local/cuda/include -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -isystem /usr/lib/x86_64-linux-gnu/openmpi/include -fopenmp -g -pthread -std=c++14 -o jacobi.cpp.o -c jacobi.cpp
c++ -pthread jacobi.cpp.o jacobi_kernels.cu.o -o mpi -L/usr/local/cuda/targets/x86_64-linux/lib/stubs /usr/local/cuda/lib64/libnvToolsExt.so /usr/local/cuda/lib64/libcudart.so /usr/lib/x86_64-linux-gnu/libcuda.so /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so /usr/lib/gcc/x86_64-linux-gnu/10/libgomp.so /usr/lib/x86_64-linux-gnu/libpthread.so -lcudadevrt -lcudart_static -lrt -lpthread -ldl
```
The main difference from your Makefile is that jacobi.cpp is compiled directly with the host-side C++ compiler, not the mpicxx wrappers. But... this is supposed to be legit, right? These lines are adaptations of what CMake generates.

Anyway, it does get built, and runs, but at the end of the first 1000 iterations, has a segmentation fault at:
```
        MPI_CALL(MPI_Sendrecv(a_new + iy_start * nx, nx, MPI_REAL_TYPE, top, 0,
                              a_new + (iy_end * nx), nx, MPI_REAL_TYPE, bottom, 0, MPI_COMM_WORLD,
                              MPI_STATUS_IGNORE));
```
With the stack being:
```
__memmove_avx_unaligned_erms 0x00007f03d477fb12
<unknown> 0x00007f03d0252280
mca_pml_ob1_recv_request_get_frag 0x00007f03d003fcbf
mca_pml_ob1_recv_request_progress_rget 0x00007f03d0040106
<unknown> 0x00007f03d003ba2b
<unknown> 0x00007f03d003bcc0
<unknown> 0x00007f03d0252983
mca_pml_ob1_send_request_start_rdma 0x00007f03d0048131
mca_pml_ob1_send 0x00007f03d00389ef
PMPI_Sendrecv 0x00007f03d4da3ece
main jacobi.cpp:239
__libc_start_main 0x00007f03d4643d0a
_start 0x000055becffc4d8a
```

**Comment by jirikraus** [comment]
@eyalroz does it work if you use the mpi compiler wrapper `mpicxx`? You can make this work by using the host-side C++ compiler but need to be careful to set the right preprocessor defines and include paths for your MPI. Something `mpicxx` does for you. For OpenMPI you can use the `--showme` command line flag of the compiler wrappers to check. See e.g. the man page of `mpicxx`: https://www.open-mpi.org/doc/current/man1/mpicxx.1.php

**Comment by eyalroz** [comment]
I also get this same behavior if I make the functions `launch_initialize_boundaries()` and `launch_jacobi_kernel()` do nothing, so that I don't use NVCC at all.

Oh, an important point! I should also mention I don't use mpirun, I just run the executables directly. - and if I do use `mpirun -np 1` or `mpirun -np 2`, there's no crash.

**Comment by jirikraus** [comment]
> I also get this same behavior if I make the functions launch_initialize_boundaries() and launch_jacobi_kernel() do nothing, so that I don't use NVCC at all.

My comment was not about NVCC. It was about the need to use `mpicxx` as otherwise you can easily get an include path or define wrong.

> Oh, an important point! I should also mention I don't use mpirun, I just run the executables directly. - and if I do use `mpirun -np 1` or `mpirun -np 2`, there's no crash.

OK than that is the issue. You need to use a launcher compatible with your MPI. In any case since to my understanding with the Makefiles provided by this project it works I am closing this.
