### ISSUE TITLE
Performance issue with NVSHMEM example

### ISSUE THREAD

**Issue by covoge** [NVIDIA/multi-gpu-programming-models#17]
Hello,

I am observing significant performance issues running the `nvshmem` benchmark over InfiniBand. I'm running RHEL 7.9 on two compute nodes, each with 8x NVIDIA A100-SXM4 (40 GB RAM) and 2x AMD EPYC CPU 7352 (24 cores). The A100s inside the compute nodes are connected via NVLink, the compute nodes are connected via InfiniBand.

I'm configuring the `nvshmem` example with nx = ny = 32768. Running it with two GPUs on a single compute node yields the expected result of about half the single GPU runtime (from ~10 seconds to ~5 seconds). Running the same example with two GPUs on 2 compute nodes (so one GPU per compute node) results in a runtime of ~43 seconds, so about 4.3 times slower than the single GPU version.

I'm NVSHMEM 2.5.0 and OpenMPI 4.1.1. Do you have any idea what could cause this issue? Did I make a mistake while configuring/installing NVSHMEM?

I'd greatly appreciate any tips or suggestions.

**Comment by akhillanger** [comment]
@pazkaI for multinode runs please use nvshmem_opt directory as that is optimized for multinode runs.

**Comment by covoge** [comment]
@akhillanger thanks for the suggestion - I tried the `nvshmem_opt` version with multiple compute nodes and it seems to scale as expected.

**Comment by zzzlxhhh** [comment]
Hi! I'm also trying to run `nvshmem` on multi-node environment. However, I encountered an error that two GPUs from two different nodes could not access each other. 
When I run my application on SLURM using:
```
mpirun -np $SLURM_NTASKS $APP_PATH $DATA $SLURM_NTASKS
``` 
I got the following error report:
```
mpi_info: rank: 0, nranks: 2
mpi_info: rank: 1, nranks: 2
PE-0, local_gpu_num: 1, local_gpu_id: 0
PE-1, local_gpu_num: 1, local_gpu_id: 0

src/topo/topo.cpp:61: [GPU 1] Peer GPU 0 is not accessible, exiting ... 
src/init/init.cpp:276: non-zero status: 3 building transport map failed 
src/mem/mem.cpp:nvshmem_malloc:342: nvshmem initialization failed, exiting 
src/topo/topo.cpp:61: [GPU 0] Peer GPU 1 is not accessible, exiting ... 
src/init/init.cpp:276: non-zero status: 3 building transport map failed 
src/mem/mem.cpp:nvshmem_malloc:342: nvshmem initialization failed, exiting 
``` 
To clarify, these two nodes have an IB connection. Does the problem come from my `mpirun` command? Or do I have to configure nvshmem to notify it to use the IB connection?
It's very glad to see that you have successfully run NVSHMEM on multi-node. And, could you please help me solve this problem?

**Comment by jirikraus** [comment]
@zzzlxhhh can you share a bit more about your system configuration? What GPUs are you using? Are you using dmabuf or nvidia-peermem to setup GPUDirect RDMA? Working GPUDirect RDMA is a requirement for multi node NVSHMEM.

**Comment by zzzlxhhh** [comment]
Thanks for your reply. I'm running my application on two nodes each with 8 A800 GPUs on the school cluster. It's very tricky to solve all the dependencies required for NVSHMEM on multi-node since I’m not the cluster administrator. I'm going to use Nvidia HPC SDK to build a container to run my application.

To clarity, I can run my application successfully on single-node multi-GPU.

By the way, to enable `GPUDirect RDMA` means I have to install GDRCopy and `nvidia-peermem`? Also, before `nvidia-peermem`, there exists `nv_peer_mem`. Do all NVSHMEM versions support the latest `nvidia-peermem`? Or some versions of NVSHMEM rely on `nv_peer_mem`?

**Comment by zzzlxhhh** [comment]
My main concern is about the installation guide provided by Nvidia. It is unclear what installation settings should be met to run NVSHMEM on multi-node multi-GPU platform, since cross-node communication is more complicated than single-node multi-GPU. They list so many `optional` settings. 
![Image](https://github.com/user-attachments/assets/c7c1ba5c-f941-493e-8c5d-f545bac07056)

**Comment by zzzlxhhh** [comment]
To update, I use nvidia hpc sdk container `22.11-devel-cuda11.8-ubuntu22.04` to run my application to ensure that all the dependencies are installed properly. However, I still run into trouble.
The SLURM script is as follows:
```
#!/bin/bash  
#SBATCH -p g078t2  
#SBATCH -N 2  
#SBATCH --ntasks=2  
#SBATCH --ntasks-per-node=1  
#SBATCH --gres=gpu:1  
#SBATCH --time=10:00  
#SBATCH --comment=idmg_bupt  

mpirun -n 2 singularity exec --nv -B /usr/local/nvidia \
        ~/nvsdk_118.sif ./coco.sh
```
The content in ./coco.sh is to call singularity to run my application:
```
#!/bin/bash
export LD_LIBRARY_PATH=/usr/local/nvidia/lib:$LD_LIBRARY_PATH
export PATH=/usr/local/nvidia:$PATH
source /usr/share/lmod/lmod/init/bash
module load nvhpc/22.11

~/distSpMM/AdaCo_AE/build/distSpMM com-Amazon 2 32 0 0
```
However, the error report is:
```
INFO:    Mounting image with FUSE.
INFO:    Mounting image with FUSE.
WARNING: underlay of /usr/bin/nvidia-smi required more than 50 (428) bind mounts
WARNING: underlay of /usr/bin/nvidia-smi required more than 50 (428) bind mounts
--------------------------------------------------------------------------
WARNING: No preset parameters were found for the device that Open MPI
detected:

  Local host:            gpu8
  Device name:           mlx5_0
  Device vendor ID:      0x02c9
  Device vendor part ID: 4123

Default device parameters will be used, which may result in lower
performance.  You can edit any of the files specified by the
btl_openib_device_param_files MCA parameter to set values for your
device.

NOTE: You can turn off this warning by setting the MCA parameter
      btl_openib_warn_no_device_params_found to 0.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
WARNING: There are more than one active ports on host 'gpu8', but the
default subnet GID prefix was detected on more than one of these
ports.  If these ports are connected to different physical IB
networks, this configuration will fail in Open MPI.  This version of
Open MPI requires that every physically separate IB subnet that is
used between connected MPI processes must have different subnet ID
values.

Please see this FAQ entry for more details:

  http://www.open-mpi.org/faq/?category=openfabrics#ofa-default-subnet-gid

NOTE: You can turn off this warning by setting the MCA parameter
      btl_openib_warn_default_gid_prefix to 0.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
No OpenFabrics connection schemes reported that they were able to be
used on a specific port.  As such, the openib BTL (OpenFabrics
support) will be disabled for this port.

  Local host:           gpu8
  Local device:         mlx5_2
  Local port:           1
  CPCs attempted:       rdmacm, udcm
--------------------------------------------------------------------------
mpi_info: rank: 0, nranks: 2
mpi_info: rank: 1, nranks: 2
PE-1, local_gpu_num: 1, local_gpu_id: 0
PE-0, local_gpu_num: 1, local_gpu_id: 0
group_size is set to 0 for rowSpMM
graph_name: com-Amazon, num_GPUs: 2, dim: 32 
IO read from bin time: 42.304001 ms
[gpu9:16180] *** Process received signal ***
[gpu9:16180] Signal: Segmentation fault (11)
[gpu9:16180] Signal code: Invalid permissions (2)
[gpu9:16180] Failing at address: 0x14724700e790
[gpu9:16180] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x147247bf0520]
[gpu9:16180] [ 1] [0x14724700e790]
[gpu9:16180] *** End of error message ***
[gpu8:16579] *** Process received signal ***
[gpu8:16579] Signal: Segmentation fault (11)
[gpu8:16579] Signal code: Invalid permissions (2)
[gpu8:16579] Failing at address: 0x147ff9535790
[gpu8:16579] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x147ff99f0520]
[gpu8:16579] [ 1] [0x147ff9535790]
[gpu8:16579] *** End of error message ***
/home/u2022110987/distSpMM/AdaCo_AE/multi_node/coco.sh: line 7: 16579 Segmentation fault      (core dumped) ~/distSpMM/AdaCo_AE/build/distSpMM com-Amazon 2 32 0 0
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
/home/u2022110987/distSpMM/AdaCo_AE/multi_node/coco.sh: line 7: 16180 Segmentation fault      (core dumped) ~/distSpMM/AdaCo_AE/build/distSpMM com-Amazon 2 32 0 0
[gpu8:16510] 7 more processes have sent help message help-mpi-btl-openib.txt / no device params found
[gpu8:16510] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[gpu8:16510] 5 more processes have sent help message help-mpi-btl-openib.txt / default subnet prefix
[gpu8:16510] 3 more processes have sent help message help-mpi-btl-openib-cpc-base.txt / no cpcs for port
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[37160,1],0]
  Exit code:    139
--------------------------------------------------------------------------
```
Does it because the `openmpi-4.1.1` in the host is not the same with `openmpi-4.1.5a1` in the sigularity container? Should I recompile an openmpi on the host side?

**Comment by jirikraus** [comment]
@zzzlxhhh sorry I can't help you much with solving what the issue with your container is. Regarding the NVSHMEM requirements: For multi node runs you need one of:

- Mellanox OFED and nvidia-peermem 
- UCX which at least for performant exectuion also requires Mellanox OFED and nvidia-peermem if you are using a NVIDIA IB network
- libfabrics e.g. if you are running on a system with slingshot 11.

These dependencies are described as optional because you can use NVSHMEM single node without them. As described if GDRCopy is needed or not depends on your use of atomics. 

Hope this helps.

**Comment by zzzlxhhh** [comment]
Thank you so much! Your explanation helps a lot. It's much more clear.

**Comment by zzzlxhhh** [comment]
> [@zzzlxhhh](https://github.com/zzzlxhhh) sorry I can't help you much with solving what the issue with your container is. Regarding the NVSHMEM requirements: For multi node runs you need one of:
> 
> * Mellanox OFED and nvidia-peermem
> * UCX which at least for performant exectuion also requires Mellanox OFED and nvidia-peermem if you are using a NVIDIA IB network
> * libfabrics e.g. if you are running on a system with slingshot 11.
> 
> These dependencies are described as optional because you can use NVSHMEM single node without them. As described if GDRCopy is needed or not depends on your use of atomics.
> 
> Hope this helps.

Sorry to bother you again! I deeply appreciate your kind response! 

I have prepared a system with `Mellanox OFED and nvidia-peermem`. However, there are still errors when running on multi-node multi-GPU. (running on single-node multi-GPU is OK).

The error report is:
```
Running on nodes: gpu[8-9]
Executable path: ./distSpMM
mpi_info: rank: 0, nranks: 2
mpi_info: rank: 1, nranks: 2
PE-0, local_gpu_num: 1, local_gpu_id: 0
PE-1, local_gpu_num: 1, local_gpu_id: 0
group_size: 1 for XpMM
graph_name: com-Amazon, num_GPUs: 2, dim: 32 
PE-0, l_split_ratio:1.001 
PE-1, l_split_ratio:1.001 
WARN: IB: read failed in ib_roce_get_version_num: Invalid argument
WARN: IB: read failed in ib_roce_get_version_num: Invalid argument
WARN: IB: read failed in ib_roce_get_version_num: Invalid argument
WARN: IB: read failed in ib_roce_get_version_num: Invalid argument
WARN: IB: read failed in ib_roce_get_version_num: Invalid argument
WARN: IB: read failed in ib_roce_get_version_num: Invalid argument
WARN: IB: read failed in ib_roce_get_version_num: Invalid argument
WARN: IB: read failed in ib_roce_get_version_num: Invalid argument
PE-1, local_if_nonempty_nvshmem: 0x10038c80600, remote_if_nonempty_d: (nil)
PE-0, local_if_nonempty_nvshmem: 0x10038c80600, remote_if_nonempty_d: (nil)
PE-1, local_row:150255 remote_col:149059 reduce_cnt:0 
PE-0, local_row:150160 remote_col:148809 reduce_cnt:0 
IO read from bin time: 463.783997 ms
/home/u2022110987/lib_src/nvshmem_src/src/modules/transport/ibrc/ibrc.cpp:1025: non-zero status: 4 ibv_poll_cq failed, status: 4

/home/u2022110987/lib_src/nvshmem_src/src/modules/transport/ibrc/ibrc.cpp:1085: non-zero status: 7 progress_send failed, outstanding_count: 1023

/home/u2022110987/lib_src/nvshmem_src/src/modules/transport/ibrc/ibrc.cpp:1115: non-zero status: 7 check_poll failed 

/home/u2022110987/lib_src/nvshmem_src/src/include/internal/host/nvshmem_internal.h:nvshmemi_process_multisend_rma:182: aborting due to error in process_channel_dma

/home/u2022110987/lib_src/nvshmem_src/src/modules/transport/ibrc/ibrc.cpp:1025: non-zero status: 4 ibv_poll_cq failed, status: 4

/home/u2022110987/lib_src/nvshmem_src/src/modules/transport/ibrc/ibrc.cpp:1085: non-zero status: 7 progress_send failed, outstanding_count: 1023

/home/u2022110987/lib_src/nvshmem_src/src/modules/transport/ibrc/ibrc.cpp:1115: non-zero status: 7 check_poll failed 

/home/u2022110987/lib_src/nvshmem_src/src/include/internal/host/nvshmem_internal.h:nvshmemi_process_multisend_rma:182: aborting due to error in process_channel_dma

--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[59241,1],1]
  Exit code:    255
--------------------------------------------------------------------------

```
To emphasize, the main issues are:
```
/home/u2022110987/lib_src/nvshmem_src/src/modules/transport/ibrc/ibrc.cpp:1025: non-zero status: 4 ibv_poll_cq failed, status: 4

/home/u2022110987/lib_src/nvshmem_src/src/modules/transport/ibrc/ibrc.cpp:1085: non-zero status: 7 progress_send failed, outstanding_count: 1023

/home/u2022110987/lib_src/nvshmem_src/src/modules/transport/ibrc/ibrc.cpp:1115: non-zero status: 7 check_poll failed 

/home/u2022110987/lib_src/nvshmem_src/src/include/internal/host/nvshmem_internal.h:nvshmemi_process_multisend_rma:182: aborting due to error in process_channel_dma
```
So, I checked the corresponding Q&A in [NVSHMEM FAQ](https://docs.nvidia.com/nvshmem/api/faq.html). 
![Image](https://github.com/user-attachments/assets/9ef80c66-6659-487d-8579-535f04013673)

The Q&A is still very unclear. What behavior could trigger this issue?
Does `Error or status: 4 - Local Protection Error` mean I have some wrong operation about the GPU shared memory? 

More specifically, in my case, I use in-kernel registers as the local buffer to store the remote data from another `PE(GPU)` as follows:
```
input is registered as nvshmem
float *tmp2 = (float *)&tmp[warpPerBlock * dim];
nvshmemx_float_get_warp((float *)&tmp2[blk_wid * dim], &input[r_offset * dim], dim, r_GPUid);
```
To my understanding, this behavior is not allowed in multi-node multi-GPU NVSHMEM, but allowed in single-node multi-GPU NVSHMEM? 

Am I right? Could you please give some suggestions about my next step? Whether should I modify all the code? My project is huge, so I have to evaluate the possible time I have to invest to modify the code.

**Comment by zzzlxhhh** [comment]
Problem solved. This is indeed caused by using local scratchpad memory as the buffer to receive remote data.

**Comment by jirikraus** [comment]
Great and thanks for closing the loop @zzzlxhhh . In general please use our developer forums for these kind of questions as they are not about the code in this repository. For NVSHMEM starting new Topic in the GPU-Accelerated Libraries Category: https://forums.developer.nvidia.com/c/accelerated-computing/gpu-accelerated-libraries/12 with the Tag nvshmem would be best.

**Comment by zzzlxhhh** [comment]
Thanks for your suggestions! So sorry to bother you again. However, I also encountered a severe performance drop when running application on multi-node multi-GPU platform.  This issue has not yet been reported in the nvida developer forum. I will later post my issue in the developer forum too. This is also encountered by @covoge. And @akhillanger suggests to use nvshmem_opt directory, but I cannot find this directory. 

> Hello,
> 
> I am observing significant performance issues running the `nvshmem` benchmark over InfiniBand. I'm running RHEL 7.9 on two compute nodes, each with 8x NVIDIA A100-SXM4 (40 GB RAM) and 2x AMD EPYC CPU 7352 (24 cores). The A100s inside the compute nodes are connected via NVLink, the compute nodes are connected via InfiniBand.
> 
> I'm configuring the `nvshmem` example with nx = ny = 32768. Running it with two GPUs on a single compute node yields the expected result of about half the single GPU runtime (from ~10 seconds to ~5 seconds). Running the same example with two GPUs on 2 compute nodes (so one GPU per compute node) results in a runtime of ~43 seconds, so about 4.3 times slower than the single GPU version.
> 
> I'm NVSHMEM 2.5.0 and OpenMPI 4.1.1. Do you have any idea what could cause this issue? Did I make a mistake while configuring/installing NVSHMEM?
> 
> I'd greatly appreciate any tips or suggestions.

To clarify, the cross node connection is based on IB with around 20GB/s bandwidth, intra-node GPU connection is based on NVLINK with around 180 GB/s bandwidth. However, the performance drop drastically, from 0.1 ms (with 8 GPUs in 1 node) to 70 ms (2 nodes each with 4 GPUs). What could cause these performance degradation?

**Comment by jirikraus** [comment]
> Thanks for your suggestions! So sorry to bother you again. However, I also encountered a severe performance drop when running application on multi-node multi-GPU platform. This issue has not yet been reported in the nvida developer forum. I will later post my issue in the developer forum too. This is also encountered by [@covoge](https://github.com/covoge). And [@akhillanger](https://github.com/akhillanger) suggests to use nvshmem_opt directory, but I cannot find this directory.

That is because the two `nvshmem` version have been merged into one. You can get the behavior of the `nvshmem_opt` variant by using `-use_block_comm` command line option. See https://github.com/NVIDIA/multi-gpu-programming-models?tab=readme-ov-file#run-instructions in the project `README.md`.

The reason for the performance degradation is explained in the second half of the CUDA Graphs and Device Initiated Communication  with NVSHMEM session of the ISC/SC Tutorial [Efficient Distributed GPU Programming for Exascale](https://github.com/FZJ-JSC/tutorial-multi-gpu) you can find the slides of that session [here](https://github.com/FZJ-JSC/tutorial-multi-gpu/tree/main/09-L_CUDA_Graphs_and_Device-initiated_Communication_with_NVSHMEM).

You find some more details about the IBGDA Transport of NVSHMEM in: https://developer.nvidia.com/blog/improving-network-performance-of-hpc-systems-using-nvidia-magnum-io-nvshmem-and-gpudirect-async/ 

Hope this helps
