### ISSUE TITLE
How to veify NVIDIA IMEX daemon?

### ISSUE THREAD

**Issue by yupatrick22** [NVIDIA/multi-gpu-programming-models#19]
Hi,

I am running a test with multi_node_P2P on a single node with H100x8, but get a error as below
![Image](https://github.com/user-attachments/assets/fa490957-1e37-4769-99f2-1f95354f44e2)
according to the readme, this code has requirements of CUDA 12.4, a CUDA Driver 550.54.14, which is ok for my system
![Image](https://github.com/user-attachments/assets/afa1837e-d90e-4f39-83b7-4c03f2cdf284)
The last requirement is the NVIDIA IMEX, after google this, I almost get nothing about IMEX, neither from NVIDIA website. And, I think the error is caused by this IMEX deamon.

My question is how to check whether NVIDIA IMEX daemon is runing or not on my system, and if not, how to start or configure it?

**Comment by jirikraus** [comment]
Yes, documentation about IMEX is currently sparse. We are working on that. You are also right that the error is probably related to IMEX channels not being set up as needed. IMEX is a new IPC (security) model and needs to be configured to each user's needs. The GPU driver/CUDA does not have access to the full context of the user deployment, so it does not set up IMEX channels by default. If configured incorrectly, this could lead to potential security vulnerabilities. Therefore, we place the responsibility on users and administrators. For everything to work properly two things are required:

1. The `nvidia-caps-imex-channels` char device is available. This device should be created by the NVIDIA GPU driver. You can check for that with
    ````
    # cat /proc/devices | grep nvidia
    195 nvidia
    195 nvidiactl
    234 nvidia-caps-imex-channels
    509 nvidia-nvswitch

2. `/dev/nvidia-caps-imex-channels/channel*` device nodes exist and are accessible by the user launching the application using `CU_MEM_HANDLE_TYPE_FABRIC`. As said these are not automatically created so that must be handled by the administrator.

A default channel (e.g. `channel0`) can be set up if the use case involves a single user. However, for multi-user resource isolation, an IMEX channel is required for each user, as the IMEX security operates at the user level. When exporter and importer CUDA processes have been granted access to the same IMEX channel, they can securely share memory. 

The two recommended ways to set up IMEX channels are

1. Using `mknod`:  e.g. create `channel0` with the major number from `/proc/devices` do
    ```
    mknod /dev/nvidia-caps-imex-channels/channel0 c <major number> 0.  
    ```
2. For a single user development system set `NVreg_CreateImexChannel0` as module parameter for the NVIDIA driver. If set, the IMEX `channel0` will be created automatically when an application (for example, `nvidia-smi`, `nvidia-persistenced`, or a CUDA application) is run.

Side note:

In older drivers, we provided an option to create an IMEX channel using `nvidia-modprobe` with the `-i` option for convenience. However, we no longer recommend using this option as it will be removed in upcoming drivers. This is important to mention because, when configuring a system for multiple IMEX jobs/users, it is essential to ensure `nvidia-modprobe` is not accessible to regular users. Otherwise, any user could override the admin's IMEX channel setup via `nvidia-modprobe`, potentially leading to security issues. To prevent this, you must restrict access to `nvidia-modprobe` to users (e.g. through containers etc) or set `NVreg_ModifyDeviceFiles`, allowing you to manage/control the NVIDIA `/dev` files directly and prevent unauthorized modifications by users.

Once support for IMEX channels through `nvidia-modprobe` is removed, this additional step will no longer be necessary at least from the IMEX channel perspective. However, if you are isolating GPUs among users/jobs, it will still be essential to follow the above steps to maintain proper isolation/security among the users/jobs.

Closing this as there is no issue with the repository.
