### ISSUE TITLE
Seg faulting MPI test

### ISSUE THREAD

**Issue by chchang6** [NVIDIA/multi-gpu-programming-models#3]
Running with OpenMPI 3.1.3 or HPE-MPI/MPT 2.17 or 2.20 under Slurm, get seg fault at cycle 900.

[cchang@el3 mpi]$ srun --ntasks 2 --time=5:00 --account=hpcapps --partition=debug --gres=gpu:2 ./jacobi
srun: job 1368607 queued and waiting for resources
srun: job 1368607 has been allocated resources
Single GPU jacobi relaxation: 1000 iterations on 7168 x 7168 mesh with norm check every 1 iterations
    0, 21.164557
  100, 0.593927
  200, 0.354291
  300, 0.261674
  400, 0.211003
  500, 0.178542
  600, 0.155754
  700, 0.138766
  800, 0.125551
  900, 0.114949
MPT ERROR: Rank 0(g:0) received signal SIGSEGV(11).

Backtrace for OpenMPI 3.1.3 run with single rank:
[r104u33:4212 :0] Caught signal 11 (Segmentation fault)
==== backtrace ====
 2 0x000000000006858c mxm_handle_error()  /var/tmp/OFED_topdir/BUILD/mxm-3.7.3111/src/mxm/util/debug/debug.c:641
 3 0x0000000000068adc mxm_error_signal_handler()  /var/tmp/OFED_topdir/BUILD/mxm-3.7.3111/src/mxm/util/debug/debug.c:616
 4 0x0000000000035270 killpg()  ??:0
 5 0x000000000014ad89 __memcpy_ssse3_back()  :0
 6 0x000000000005b690 mxm_proto_set_data_buf_long()  /var/tmp/OFED_topdir/BUILD/mxm-3.7.3111/src/mxm/proto/proto_ops.c:315
 7 0x00000000000659e7 mxm_self_channel_progress()  /var/tmp/OFED_topdir/BUILD/mxm-3.7.3111/src/mxm/tl/self/self_tl.c:183
 8 0x000000000005629b mxm_proto_conn_switch_to_next_channel_finalize()  /var/tmp/OFED_topdir/BUILD/mxm-3.7.3111/src/mxm/proto/proto_conn.c:168
 9 0x00000000000563b9 mxm_proto_conn_connect_loopback_invoked()  /var/tmp/OFED_topdir/BUILD/mxm-3.7.3111/src/mxm/proto/proto_conn.c:407
10 0x0000000000053d4c mxm_invoke_dispatcher()  /var/tmp/OFED_topdir/BUILD/mxm-3.7.3111/src/mxm/core/mxm.c:256
11 0x00000000000544ca mxm_notifier_chain_call()  /var/tmp/OFED_topdir/BUILD/mxm-3.7.3111/src/./mxm/util/datatype/callback.h:74
12 0x00000000001b0d07 mca_pml_yalla_progress()  ??:0
13 0x000000000005a91c opal_progress()  ??:0
14 0x00000000000547ec mxm_wait()  /var/tmp/OFED_topdir/BUILD/mxm-3.7.3111/src/mxm/core/mxm.c:369
15 0x00000000001b3311 mca_pml_yalla_send()  ??:0
16 0x00000000000b09fe PMPI_Sendrecv()  ??:0
17 0x000000000040a792 main()  ??:0
18 0x0000000000021c05 __libc_start_main()  ??:0
19 0x0000000000409849 _start()  ??:0
===================
srun: error: r104u33: task 0: Segmentation fault (core dumped)

**Comment by akhillanger** [comment]
@chchang6 it looks like that your MPI is not cuda-aware? For example, OpenMPI needs to be build with --with-cuda option.

**Comment by chchang6** [comment]
Should the OpenMPI example have been able to get to iteration 900 without being CUDA aware? Our OpenMPI 2.1.5 and 1.10.7 builds seg fault immediately, so that may well be the issue.

I'll check with HPE MPI, it appears an environment variable may need to be set. Thanks!

**Comment by akhillanger** [comment]
The Jacobi program first runs single gpu version (the output corresponds to this) that does not use MPI. After that, it runs the multi-gpu version and the program seg faults immediately.

**Comment by chchang6** [comment]
That must be it. And I just tested MPT with the MPI_USE_CUDA=true environment setting, and it worked perfectly. So I think you nailed the cause, thank you!

**Comment by akhillanger** [comment]
Good to know that it works now. Also, try the `nvshmem_opt` version in that repo. It gives superior performance over mpi version. You can get nvshmem here: https://developer.nvidia.com/nvshmem

**Comment by chchang6** [comment]
Hi Akhil--Actually, I double-checked and all the OpenMPI builds we're using (1.10.7, 2.1.5, 3.1.3) were built CUDA-aware. Still generating seg faults though. Some of the ompi_info cuda options follow. Not sure how mpi_built_with_cuda_support is true but mpi_cuda_support is false.

mca:mpi:base:param:mpi_built_with_cuda_support:value:true
mca:mpi:base:param:mpi_built_with_cuda_support:source:default
mca:mpi:base:param:mpi_built_with_cuda_support:status:read-only
mca:mpi:base:param:mpi_built_with_cuda_support:level:4
mca:mpi:base:param:mpi_built_with_cuda_support:help:Whether CUDA GPU buffer support is built into library or not
mca:mpi:base:param:mpi_built_with_cuda_support:enumerator:value:0:false
mca:mpi:base:param:mpi_built_with_cuda_support:enumerator:value:1:true
mca:mpi:base:param:mpi_built_with_cuda_support:deprecated:no
mca:mpi:base:param:mpi_built_with_cuda_support:type:bool
mca:mpi:base:param:mpi_built_with_cuda_support:disabled:false
mca:mpi:base:param:mpi_cuda_support:value:false
mca:mpi:base:param:mpi_cuda_support:source:environment
mca:mpi:base:param:mpi_cuda_support:status:writeable
mca:mpi:base:param:mpi_cuda_support:level:4
mca:mpi:base:param:mpi_cuda_support:help:Whether CUDA GPU buffer support is enabled or not

**Comment by akhillanger** [comment]
@Akshay-Venkatesh - any thoughts?

**Comment by Akshay-Venkatesh** [comment]
@chchang6 You may want to check with system admin if mca param `opal_cuda_support` has been set to false. The other thing is that UCX is the preferred way to use OpenMPI for CUDA-Aware MPI. UCX sections in the following links should help:
https://www.open-mpi.org/faq/?category=buildcuda
https://www.open-mpi.org/faq/?category=runcuda

**Comment by chchang6** [comment]
@Akshay-Venkatesh Thank you very much, you hit exactly on 2 of our issues. opal_cuda_support is false, and OpenMPI was built without UCX.

**Comment by chchang6** [comment]
Just wanted to wrap this thread by reporting I built OpenMPI 3.1.3 with UCX and CUDA support, and was able to get the tests running over multiple GPUs on single and multiple nodes. Thanks again for your help!

**Comment by akhillanger** [comment]
Awesome! Thanks for the update.
