### ISSUE TITLE
Question about halo exchange

### ISSUE THREAD

**Issue by ghost** [NVIDIA/multi-gpu-programming-models#6]
Hi, I have a question about the [halo exchange](https://github.com/NVIDIA/multi-gpu-programming-models/blob/efa4187a48be601f4ab9922e7807707279c32f12/single_threaded_copy/jacobi.cu#L265). Why does the halo exchange loop 5 times?    The work in each iteration seems to be identical.

Thanks.

**Comment by akhillanger** [comment]
Yes, this looks redundant to me. @jirikraus ?

**Comment by jirikraus** [comment]
Those are just warm up calls. The choice to execute the code 5 times is arbitrary. Does that answer the question?

**Comment by ghost** [comment]
I see. Thanks for your answering!
